- name: Install and start Apache server
  hosts: web
  become: yes

  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Create a custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from Ansible on EC2!</h1>"

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes